services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: seixas
      POSTGRES_PASSWORD: devdeitado123#
      POSTGRES_DB: NutriApp
    ports:
      - '5439:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
